system_prompt: "When creating prompts for Genie, ensure that you are passing current prompt unchanged to Genie. This will help generate accurate and efficient SQL queries. If you are processing tool results from Genie, remember to clean the output and always mention which Genie Space was used. If it mentions SQL query but value is missing, mention that Genie didn't provide SQL output."
secret_scope: Add your Databricks Workspace secret scope here
devops_token: Add your DevOps token secret here
devops_organization: Add DevOps organization name here
devops_project: Add DevOps project name here
devops_connection: Add DevOps connection name here

tools:
  genie_123456789:
    type: function
    function:
      name: genie_123456789
      description: "Contains all metadata information on Databricks, like jobs and costs"
      parameters:
        type: object
        properties:
          prompt:
            type: string
            description: "Write an optimized prompt to fetch the requested information from Genie Space."
        required:
          - prompt
        returns:
          type: "string"
          description: "Genie Space results"

  genie_987654321:
    type: function
    function:
      name: genie_987654321
      description: "Contains all information on customers, like profitability"
      parameters:
        type: object
        properties:
          prompt:
            type: string
            description: "Write an optimized prompt to fetch the requested information from Genie Space."
        required:
          - prompt
        returns:
          type: "string"
          description: "Genie Space results"

  create_update_devops_ticket:
    type: function
    function:
      name: create_update_devops_ticket
      description: "A tool dedicated for Azure DevOps ticket creation and update"
      parameters:
        type: object
        properties:
          content:
            type: string
            description: "write a content for DevOps ticket. Remove all formatting and bolding."
        required:
          - content
        returns:
          type: "string"
          description: "DevOps ticket results"

  get_documentation:
    type: function
    function:
      name: get_documentation
      description: "Get internal documentation for data enrichment"
      parameters:
        type: object
        properties:
          activation:
            type: string
            description: "Yes or No"
        required:
          - activation
        returns:
          type: "string"
          description: "Documentation results"